### ISSUE TITLE
Sieve of Erathosthenes

### ISSUE THREAD

**Issue by divya-rai-42** [ShriyanshiSrivastava/Data_Structures_For_Hacktoberfest#46]
Through this algorithm, prime numbers upto a given target can be found in O(nlog(log(n)))
Example: n=16
Output: 2 3 5 7 11 13

**Comment by ShriyanshiSrivastava** [comment]
Awesome Divya! You can go ahead and write a code that explains this algorithm.

**Comment by divya-rai-42** [comment]
Thank You :)
