### ISSUE TITLE
I want to add Lowest Common Ancestor Problem in Binary Tree

### ISSUE THREAD

**Issue by hd2342-dubey** [ShriyanshiSrivastava/Data_Structures_For_Hacktoberfest#68]
I want to add Lowest Common Ancestor Problem in Binary Tree
Please assign it to me

**Comment by ShriyanshiSrivastava** [comment]
Okay Hardik , you are good to go for it . Make sure you document your code well with appropriate use of comments. All the best !

**Comment by hd2342-dubey** [comment]
Please merge it
