### ISSUE TITLE
Graph Traversal using DFS (other than c++)

### ISSUE THREAD

**Issue by ShriyanshiSrivastava** [ShriyanshiSrivastava/Data_Structures_For_Hacktoberfest#71]
You can submit a code that uses DFS to traverse a graph. C++ code has already been added. Try another language.

**Comment by snehashukkla** [comment]
@ShriyanshiSrivastava please assign this to me, i can solve this issue

**Comment by ShriyanshiSrivastava** [comment]
@snehashukkla assigned.

**Comment by dollygupta07** [comment]
Hi,
I can do this in python. Can you please assign this to me?
Thanks.

**Comment by ShriyanshiSrivastava** [comment]
@dollygupta07 Work in Python :)

**Comment by dollygupta07** [comment]
Hi. Can you please review my PR ?
Thanks.

**Comment by OptiMus-cyber** [comment]
Yes, it will be reviewed shortly.

**Comment by OptiMus-cyber** [comment]
Show some love this repo by clicking that star button :-)
