### ISSUE TITLE
Operations on strings.

### ISSUE THREAD

**Issue by ShriyanshiSrivastava** [ShriyanshiSrivastava/Data_Structures_For_Hacktoberfest#74]
You can add a code that uses string functions like string concatenation, copying a string etc.

**Comment by YushChaudhary** [comment]
Hey Shriyanshi check my code, If it is ok then don't forget to make a label. Thanks #82

**Comment by YushChaudhary** [comment]
Hey here is another one please check #84

**Comment by ShriyanshiSrivastava** [comment]
Reviewed and merged. Good Work :)

**Comment by AbhirupB** [comment]
Hello, I have pushed a code regarding sorting strings using string library functions in C++.
Do review it.
Thank you! #91

**Comment by snehashukkla** [comment]
@ShriyanshiSrivastava  please assign this to me, i can solve this issue

**Comment by aark06** [comment]
I'd like to work on this issue in Java. Please assign it to me.

**Comment by ShriyanshiSrivastava** [comment]
@snehashukkla okay Sneha you can do this , but language should not be Python or Java.

**Comment by ShriyanshiSrivastava** [comment]
@aark06 Okay assigned.

**Comment by AbhirupB** [comment]
hello..I have pushed countSubstrings code using Python.
Do review it.
Thank You.

**Comment by RitikaKapre** [comment]
@ShriyanshiSrivastava I would like to do this to brush up my C++ skills, please assign me this.

**Comment by HimanshuSinghDhapola** [comment]
@ShriyanshiSrivastava  I would like to work on this please assign it to me.

**Comment by snehashukkla** [comment]
> @snehashukkla okay Sneha you can do this , but language should not be Python or Java.

@ShriyanshiSrivastava yes I can solve it in C++,will that be okay?

**Comment by SakshiJoshi26** [comment]
hey, I would like to work on this issue in C. Please assign it to me

**Comment by Blankita21** [comment]
Hey, I would like to work on this using C++ , kindly assign me.

**Comment by azizijunaid** [comment]
Hey, I would like to work on this using javascript , kindly assign it to me.

**Comment by ShriyanshiSrivastava** [comment]
@azizijunaid Javascript assigned.

**Comment by ShriyanshiSrivastava** [comment]
@SakshiJoshi26 C assigned.

**Comment by ShriyanshiSrivastava** [comment]
@Blankita21 assigned.

**Comment by ShriyanshiSrivastava** [comment]
@snehashukkla You can work on graph code till then.

**Comment by snehashukkla** [comment]
> @snehashukkla You can work on graph code till then.

@ShriyanshiSrivastava i have requested a pull request for bfs in C language,please review it
 regards.

**Comment by RitikaKapre** [comment]
@ShriyanshiSrivastava I have pushed my code for the above using C++,review it once, Thanks!

**Comment by OptiMus-cyber** [comment]
All requests will be reviewed as soon as possible. Keep on going.

**Comment by OptiMus-cyber** [comment]
Show some love this repo by marking that star button :-)
